[Angle_PID]
AP = 8
# 15
AI = 0.8
# 0.8
AD = 0.10
# 0.15

[Position_PID]
PP = 0.0005
# 0.0005
PI = 0.0
# 0.0
PD = 0.00006
# 0.0006
MAX_TARGET_ANGLE = 5
USE_POS_PID = False
FILTER_TARGET_ANGLE = False

[Speed_PID]
SP = 0.0008
# 0.0005
SI = 0.0
# 0.0
SD = 0.0009
# 0.0006
USE_SPEED_PID = True

[Time]
DELAY = 0.01
TIMER = 5

[Motor]
USE_MOTORS = False
USE_PROCESSED_MOTORS = False
MICROSTEPS = 8

[MPU]
COMPLEMENTARY_ALPHA = 0.98
CALIBRATE = False
FILTER_ACCEL_ANGLE = False
AVERAGE_MPU_VALUES = False
SAMPLE_TIME = 0.006
AX_OFFSET = 0.081267
AY_OFFSET = -0.019716
AZ_OFFSET = 0.101106
GX_OFFSET = 0.112204
GY_OFFSET = 0.124888
GZ_OFFSET = 0.493542

[Logging]
LOG_DATA = False

[Communication]
BROKER = 10.224.64.29
PORT = 17002
USE_5G = False